# Layer By Layer and align a trajectory along a selected axes.

In [1]:
from snow.io.xyz import read_xyz
from snow.descriptors.distributions import cut_layers

In [7]:
path='tutorial_structures/Cu247_Dh.xyz'

cu_lattice=3.615 #AA
el, coords=read_xyz(path)
print(len(el))

lbl_info=cut_layers(el, coords, cu_lattice, 'Cu', 'Cu', 'z')
print(len(lbl_info))

tot=0
for l in range(len(lbl_info)):
    print(l)
    tot=tot+lbl_info[l][3]

print(tot)
print(lbl_info)

247
12
0
1
2
3
4
5
6
7
8
9
10
11
245
[(1, np.int64(17), np.int64(17), np.int64(17)), (2, np.int64(21), np.int64(21), np.int64(21)), (3, np.int64(27), np.int64(27), np.int64(27)), (4, np.int64(21), np.int64(21), np.int64(21)), (5, np.int64(27), np.int64(27), np.int64(27)), (6, np.int64(16), np.int64(16), np.int64(16)), (7, np.int64(21), np.int64(21), np.int64(21)), (8, np.int64(27), np.int64(27), np.int64(27)), (9, np.int64(21), np.int64(21), np.int64(21)), (10, np.int64(27), np.int64(27), np.int64(27)), (11, np.int64(21), np.int64(20), np.int64(20)), (12, np.int64(1), np.int64(0), np.int64(0))]


## Rotations

In [11]:
from snow.io.xyz import write_xyz
from snow.transform.rototranslation import align_axis_to_z_and_trasl_com_in_origin, rotate_of_a_angle_arond_given_ax, find_ax_two_points

from snow.descriptors.shape_descriptors import center_of_mass

path='tutorial_structures/Cu247_Dh.xyz'
cu_lattice=3.615 #AA
el, coords=read_xyz(path)


center_of_mass_cu=
center_of_mass_pt=

conn_ax=find_ax_two_points=(center_of_mass_pt, center_of_mass_cu)
c1 = align_axis_to_z_and_trasl_com_in_origin()
cc=rotate_ax_angle(coords, (1,0,0), 30)

write_xyz(filename = '/Users/szinzani/Documents/Codici/pySNOW/tutorial/tutorial_structures/Cu247_Dh_cc.xyz', elements = el, coords = cc)

In [16]:
from snow.io.xyz import write_xyz
from snow.transform.rototranslation import align_to_axis, rotate_ax_angle


coords[:][3]

#write_xyz(filename = '/Users/szinzani/Documents/Codici/pySNOW/tutorial/tutorial_structures/Cu247_Dh_cc.xyz', elements = el, coords = cc)

array([  0.       ,   0.       , -12.7632774])

In [13]:




#########


path='tutorial_structures/Cu247_Dh.xyz'

cu_lattice=3.615 #AA
el, coords=read_xyz(path)
print(len(el))

new_coords=align_to_axis(coords, (0,1,1))
write_xyz(filename = '/Users/szinzani/Documents/Codici/pySNOW/tutorial/tutorial_structures/Cu247_Dh_rotated_1.xyz', elements = el, coords = new_coords)






print(new_coords)

new_coords_2=align_to_axis(new_coords, (0,0,1))
write_xyz(filename = '/Users/szinzani/Documents/Codici/pySNOW/tutorial/tutorial_structures/Cu247_Dh_rotated_2.xyz', elements = el, coords = new_coords_2)



247
[[  0.           0.           0.        ]
 [  0.          -1.805        1.805     ]
 [  0.          -3.61         3.61      ]
 [  0.          -5.415        5.415     ]
 [  0.          -7.22         7.22      ]
 [  0.          -9.025        9.025     ]
 [  0.         -10.83        10.83      ]
 [  0.         -12.635       12.635     ]
 [  0.         -14.44        14.44      ]
 [  0.         -16.245       16.245     ]
 [  0.         -18.05        18.05      ]
 [  0.         -19.855       19.855     ]
 [  0.         -21.66        21.66      ]
 [  0.         -23.465       23.465     ]
 [  0.         -25.27        25.27      ]
 [  0.         -27.075       27.075     ]
 [  0.         -28.88        28.88      ]
 [  2.10246687  -0.41945209   1.38554791]
 [  2.10246687  -2.22445209   3.19054791]
 [  2.10246687  -4.02945209   4.99554791]
 [  2.10246687  -5.83445209   6.80054791]
 [  2.10246687  -7.63945209   8.60554791]
 [  2.10246687  -9.44445209  10.41054791]
 [  2.10246687 -11.24945209  1

In [11]:
print(new_coords_2)

[[nan nan nan]
 [nan nan nan]
 [nan nan nan]
 [nan nan nan]
 [nan nan nan]
 [nan nan nan]
 [nan nan nan]
 [nan nan nan]
 [nan nan nan]
 [nan nan nan]
 [nan nan nan]
 [nan nan nan]
 [nan nan nan]
 [nan nan nan]
 [nan nan nan]
 [nan nan nan]
 [nan nan nan]
 [nan nan nan]
 [nan nan nan]
 [nan nan nan]
 [nan nan nan]
 [nan nan nan]
 [nan nan nan]
 [nan nan nan]
 [nan nan nan]
 [nan nan nan]
 [nan nan nan]
 [nan nan nan]
 [nan nan nan]
 [nan nan nan]
 [nan nan nan]
 [nan nan nan]
 [nan nan nan]
 [nan nan nan]
 [nan nan nan]
 [nan nan nan]
 [nan nan nan]
 [nan nan nan]
 [nan nan nan]
 [nan nan nan]
 [nan nan nan]
 [nan nan nan]
 [nan nan nan]
 [nan nan nan]
 [nan nan nan]
 [nan nan nan]
 [nan nan nan]
 [nan nan nan]
 [nan nan nan]
 [nan nan nan]
 [nan nan nan]
 [nan nan nan]
 [nan nan nan]
 [nan nan nan]
 [nan nan nan]
 [nan nan nan]
 [nan nan nan]
 [nan nan nan]
 [nan nan nan]
 [nan nan nan]
 [nan nan nan]
 [nan nan nan]
 [nan nan nan]
 [nan nan nan]
 [nan nan nan]
 [nan nan nan]
 [nan nan 